groups:
- name: PrometheusRules
  rules:
    - alert: PrometheusNotIngestingSamples
      annotations:
        description: Prometheus {{ $labels.namespace }}/{{ $labels.pod}} isn't ingesting
          samples.
        summary: Prometheus isn't ingesting samples
      expr: |
        rate(prometheus_tsdb_head_samples_appended_total{app="prometheus"}[5m]) <= 0
      for: 10m
      labels:
        severity: warning
    - alert: PrometheusInvalidConfigFile
    expr: prometheus_config_last_reload_successful{app="prometheus"} == 0
    for: 30m
    labels:
      severity: critical
    annotations:
      description: The configuration file for {{$labels.job}} at {{$labels.instance}}
        is invalid and was therefore not reloaded.
      runbook: troubleshooting/prometheus-invalid-config.md
      title: '{{$labels.job}} has an invalid config'
