groups:
- name: PrometheusRules
  rules:
    - alert: PrometheusNotIngestingSamples
      annotations:
        description: Prometheus {{ $labels.namespace }}/{{ $labels.pod}} isn't ingesting
          samples.
        summary: Prometheus isn't ingesting samples
      expr: |
        rate(prometheus_tsdb_head_samples_appended_total{app="prometheus"}[5m]) <= 0
      for: 10m
      labels:
        severity: warning
